import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const labels = {time_in:'Time in',time_out:'Time out',lunch_start:'Start lunch',lunch_end:'End lunch',break_start:'Start short break',break_end:'End short break'};
const fmt = value => value ? new Date(value).toLocaleString('en-PH',{timeZone:'Asia/Manila'}) : 'Still open';
const deviceKey = 'face-dtr.kiosk-token';
async function enrollmentImage(file){
 if(!file?.size)throw new Error('Select a reference photo.');
 if(!['image/jpeg','image/png'].includes(file.type))throw new Error('Select a JPEG or PNG reference photo.');
 if(file.size>25_000_000)throw new Error('Reference photo must be smaller than 25 MB.');
 let bitmap;try{bitmap=await createImageBitmap(file);}catch{throw new Error('Could not open this photo. Select another JPEG or PNG.');}
 try{const scale=Math.min(1,1280/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement('canvas');canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));const context=canvas.getContext('2d');context.fillStyle='#fff';context.fillRect(0,0,canvas.width,canvas.height);context.drawImage(bitmap,0,0,canvas.width,canvas.height);const encoded=canvas.toDataURL('image/jpeg',0.85).split(',')[1];if(encoded.length>1_333_332)throw new Error('Photo is still too large. Choose a smaller photo.');return encoded;}finally{bitmap.close();}
}
function App(){
 const tab=window.location.pathname.replace(/\/$/,'')==='/admin'?'admin':'kiosk';
 const [token,setToken]=useState(''),[latest,setLatest]=useState(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[camera,setCamera]=useState(false),[health,setHealth]=useState(null),[employees,setEmployees]=useState([]),[records,setRecords]=useState([]),[date,setDate]=useState(''),[capture,setCapture]=useState(''),[ready,setReady]=useState(false);
 const video=useRef(null), stream=useRef(null), cancelled=useRef(false);
 useEffect(()=>{if(tab!=='kiosk')return;let active=true;let saved;try{saved=localStorage.getItem(deviceKey);}catch{return;}if(!saved)return;fetch('/api/kiosk/access',{headers:{Authorization:`Bearer ${saved}`}}).then(async r=>{if(!active)return;if(r.ok){setToken(saved);setReady(true);}else if(r.status===401){localStorage.removeItem(deviceKey);setMessage('Device access has changed. Configure this kiosk again.');}else{setMessage('Could not restore device access. Try again when the API is available.');}}).catch(()=>{if(active)setMessage('Could not connect to the API. Reload to restore this device.');});return()=>{active=false;};},[tab]);
 useEffect(()=>{if(!ready||tab!=='kiosk')return;let active=true;fetch('/api/kiosk/latest',{headers:{Authorization:`Bearer ${token}`}}).then(async r=>{if(r.ok){const result=await r.json();if(active)setLatest(result);}}).catch(()=>{});return()=>{active=false;};},[ready,tab,token]);
 async function unlock(){await task(async()=>{await api(tab==='kiosk'?'/api/kiosk/access':'/api/employees');if(tab==='kiosk'){try{localStorage.setItem(deviceKey,token);}catch{throw new Error('Browser storage is unavailable. Enable site storage to configure this device.');}}setReady(true);});}
 function forgetDevice(){try{localStorage.removeItem(deviceKey);}catch{setMessage('Could not clear device storage. Clear this site’s browser data.');return;}setToken('');setReady(false);setLatest(null);setMessage('Device disconnected. Enter the kiosk token to configure it again.');}
 useEffect(()=>{if(!ready){stream.current?.getTracks().forEach(t=>t.stop());setCamera(false);}},[ready]);
 useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setHealth).catch(()=>setMessage('API is unavailable.'));return ()=>stream.current?.getTracks().forEach(t=>t.stop());},[]);
 async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Authorization':`Bearer ${token}`,...options.headers}});if(!r.ok){let e=await r.json().catch(()=>({}));const detail=typeof e.detail==='string'?e.detail:Array.isArray(e.detail)?e.detail.map(v=>`${v.loc?.slice(1).join('.')||'Request'}: ${v.msg}`).join('; '):`Request failed (${r.status}). Please try again.`;throw new Error(detail);}return r;}
 async function task(fn){setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);setCapture('');}}
 function stopCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;if(video.current)video.current.srcObject=null;setCamera(false);}
 async function openCamera(){if(!navigator.mediaDevices?.getUserMedia)throw new Error('Camera requires HTTPS or localhost.');stopCamera();try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:640},height:{ideal:480}},audio:false});video.current.srcObject=stream.current;await video.current.play();setCamera(true);if(window.matchMedia('(max-width: 900px)').matches)video.current.closest('.camera').scrollIntoView({behavior:'smooth',block:'center'});}catch(error){stopCamera();if(error.name==='NotAllowedError')throw new Error('Camera access is blocked. Allow camera access in your browser and Windows desktop-app camera settings, then click the attendance button again.');throw error;}}
 function frame(){if(!video.current?.videoWidth)throw new Error('Start the camera first.');const canvas=document.createElement('canvas');canvas.width=640;canvas.height=480;canvas.getContext('2d').drawImage(video.current,0,0,640,480);return canvas.toDataURL('image/jpeg',0.7).split(',')[1];}
 async function punch(action){await task(async()=>{cancelled.current=false;try{setCapture('Opening camera…');await openCamera();if(cancelled.current)throw new Error('Capture cancelled.');const challenge=await (await api('/api/challenges',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action})})).json();const frames=[];for(let i=0;i<64;i++){if(cancelled.current)throw new Error('Capture cancelled.');setCapture(`Blink once, then open your eyes · ${Math.ceil((64-i)/8)}s`);frames.push(frame());await new Promise(r=>setTimeout(r,125));}if(cancelled.current)throw new Error('Capture cancelled.');setCapture('Checking blinks and identity…');const result=await (await api('/api/punches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({challenge_id:challenge.id,frames})})).json();setMessage(`${result.employee}: ${labels[result.action]} recorded at ${fmt(result.at)}.`);setLatest(result);}finally{stopCamera();}});}
 async function refresh(){await task(async()=>{setEmployees(await (await api('/api/employees')).json());setRecords(await (await api(`/api/records${date?'?date='+date:''}`)).json());});}
 async function enroll(event){event.preventDefault();const form=event.currentTarget;await task(async()=>{const data=new FormData(form);const image=await enrollmentImage(data.get('photo'));await api('/api/employees',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:data.get('id'),name:data.get('name'),department:data.get('department'),image})});form.reset();setMessage('Employee enrolled successfully.');setEmployees(await (await api('/api/employees')).json());});}
 async function exportCsv(){await task(async()=>{const r=await api(`/api/records.csv${date?'?date='+date:''}`);const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download='attendance.csv';a.click();URL.revokeObjectURL(url);});}
 return <div className={`shell ${tab==='kiosk'?'kiosk-shell':'admin-shell'}`}><header><div className="brand">◉ <span>Face<span className="accent">DTR</span></span></div><span className="badge">EMPLOYEE ATTENDANCE</span><nav><span className="pill">{tab==='admin'?'ADMINISTRATION':'ATTENDANCE KIOSK'}</span>{tab==='admin'&&ready&&<button disabled={busy} onClick={()=>{setToken('');setReady(false);setEmployees([]);setRecords([]);setMessage('');}}>Sign out</button>}</nav></header>
 <main><div className="heading"><div><p className="eyebrow">DEMO · EG SOFTWARE</p><h1>{tab==='kiosk'?'Employee attendance':'Attendance overview.'}</h1><p className="muted">{tab==='kiosk'?'Tap an action, look at the camera, and blink once.':'Enroll employees and review work sessions.'}</p></div><div className="timezone">Asia/Manila<span>Server timestamps · UTC storage</span></div></div>
 {tab==='kiosk'&&ready?<div className="device-status"><span className="status-dot"/>Kiosk ready<span className="device-hint">Camera opens when you tap an action</span></div>:<section className="access"><label>{tab==='kiosk'?'One-time kiosk setup':'Administrator access token'}<input type="password" disabled={busy} value={token} autoComplete="off" onChange={e=>{setToken(e.target.value);setReady(false);}} placeholder="Enter the configured access token"/></label><button disabled={!token||busy} onClick={unlock}>{tab==='kiosk'?'Configure this device':'Unlock workspace'}</button><span className="muted">{tab==='kiosk'?'Remembered on this browser until disconnected.':'Admin access lasts for this visit.'}</span></section>}
 {message&&<div role="status" className="notice">{message}</div>}
 {ready&&tab==='kiosk'&&<div className="grid kiosk-grid"><section className="card camera"><div className="cardhead"><h2>Camera preview</h2><span className="pill">BLINK ONCE</span></div><div className="preview"><video ref={video} playsInline muted/><div className="capture" role="status">{capture||'Tap an attendance button to start'}</div></div>{busy&&capture&&capture!=='Checking blinks and identity…'&&<button className="secondary" onClick={()=>cancelled.current=true}>Cancel capture</button>}<p className="camera-guidance">Keep your face centered. Blink once when prompted, then wait for confirmation.</p></section>
 <section className="card attendance-panel"><p className="eyebrow">RECORD ATTENDANCE</p><h2>What would you like to record?</h2><div className="action-groups">{[{title:'Workday',actions:['time_in','time_out'],tone:'work'},{title:'Lunch',actions:['lunch_start','lunch_end'],tone:'lunch'},{title:'Short break',actions:['break_start','break_end'],tone:'break'}].map(group=><div className={`action-group ${group.tone}`} key={group.title}><h3>{group.title}</h3><div className="action-pair">{group.actions.map((action,index)=><button className={`punch-button ${index===0?'start':'end'}`} key={action} disabled={busy} onClick={()=>punch(action)}><span className="action-symbol" aria-hidden="true">{index===0?'↗':'↙'}</span><span>{labels[action]}</span></button>)}</div></div>)}</div><div className="identity" aria-live="polite"><p className="eyebrow">LAST RECORDED ATTENDANCE</p>{latest?<><strong>{latest.employee}</strong><span>{latest.department}</span><span>{labels[latest.action]} · {fmt(latest.at)}</span></>:<span>No attendance recorded yet.</span>}</div></section></div>}
 {ready&&tab==='admin'&&<><div className="grid"><section className="card"><h2>Enroll an employee</h2><form onSubmit={enroll}><label>Employee ID<input name="id" required pattern="[A-Za-z0-9_-]{1,40}" placeholder="EMP-001"/></label><label>Full name<input name="name" required maxLength="100"/></label><label>Department<input name="department" maxLength="100"/></label><label>Reference photo<input name="photo" type="file" accept="image/jpeg,image/png" required/></label><p className="muted small">Use a clear photo containing exactly one face. Enrollment requires AWS access.</p><button disabled={busy}>Enroll employee</button></form></section><section className="card"><div className="cardhead"><h2>Employees</h2><button disabled={busy} onClick={refresh}>Refresh</button></div>{employees.length?employees.map(e=><div key={e.id} className="employee"><strong>{e.name}</strong><span>{e.id} · {e.department||'No department'}</span></div>):<p className="muted">Refresh to load enrolled employees.</p>}</section></div><section className="card report"><div className="cardhead"><div><h2>Daily time records</h2><p className="muted small">Open sessions show provisional totals. Overnight shifts remain on their start date.</p></div><div className="row"><input aria-label="Shift date" type="date" value={date} onChange={e=>setDate(e.target.value)}/><button disabled={busy} onClick={refresh}>Apply</button><button className="secondary" disabled={busy} onClick={exportCsv}>Export CSV</button></div></div><div className="tablewrap"><table><thead><tr>{['Employee','Shift date','Time in','Time out','Lunch','Short breaks','Payable','Status'].map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{records.map(r=><tr key={r.id}><td>{r.name}<small>{r.employee_id}</small></td><td>{r.shift_date}</td><td>{fmt(r.started)}</td><td>{fmt(r.ended)}</td><td>{r.lunch_minutes} min</td><td>{r.break_minutes} min</td><td>{(r.payable_minutes/60).toFixed(2)} h</td><td><span className="pill">{r.incomplete?'Open':'Completed'}</span></td></tr>)}</tbody></table>{!records.length&&<p className="muted">No records loaded.</p>}</div></section></>}
 {!ready&&<section className="card welcome"><h2>Ready when you are.</h2><p className="muted">Enter your access token to open the {tab==='kiosk'?'attendance kiosk':'admin workspace'}.</p></section>}
 <footer><span>demo-face.eg-software.com</span>{tab==='kiosk'&&ready&&<details className="device-settings"><summary>Device settings</summary><button className="secondary" disabled={busy} onClick={forgetDevice}>Disconnect device</button></details>}<span>{health?`API online · Blink model ${health.blink_model_ready?'ready':'needs setup'}`:'Connecting to API…'}</span></footer></main></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
